### PR TITLE
Update dependencies, use Cargo.toml include, optimize Noise

### PR DESCRIPTION
**Pull request by ocornoc**

### CODE REVIEW

**Comment by mbillingr** [comment]
Thank you for your contribution!

Could you change the commit messages to follow [this convention](https://github.com/conventional-changelog/conventional-changelog/blob/a5505865ff3dd710cf757f50530e73ef0ca641da/conventions/angular.md)? This allows [clog](https://github.com/clog-tool/clog-cli) to automatically update the changelog.
I'd suggest the following:
- docs: fix typo
- perf: update and optimize noise audio source
- refactor: allow compatible range in dependencies
- chore: use cargo include

**Comment by ocornoc** [comment]
Sure thing, I'll do it within a few hours.

**Comment by ocornoc** [comment]
Done!

**Comment by mbillingr** [comment]
Thanks a lot, much appreciated!

**Pull request merged**
